### ISSUE TITLE
Error checking $DISPLAY ?

### ISSUE THREAD

**Issue by davidsierradz** [kutsan/zsh-system-clipboard#18]
https://github.com/kutsan/zsh-system-clipboard/blob/43d1f939cbaf0d46744a0ce12828935fac7298d3/zsh-system-clipboard.zsh#L40

From [12 Conditional Expressions (zsh)](http://webcache.googleusercontent.com/search?q=cache:scrMq1hMPeAJ:zsh.sourceforge.net/Doc/Release/Conditional-Expressions.html+&cd=1&hl=en&ct=clnk&gl=co&client=firefox-b):

```
-z string

    true if length of string is zero.
```

I think this is checking if there is not a display available then exit (correct me if wrong), my `$DISPLAY` shows `:0`

```zsh
echo $DISPLAY
:0
```

So this code enters the `if`, when I remove the `!`, the script functions correctly, am I doing something wrong?

**Comment by doronbehar** [comment]
Thanks for the report, I forgot to push that commit. Feel free to reopen if you experience similar issues.

**Comment by blaenk** [comment]
So not sure what's going on but this script only works for me if I `export DISPLAY=something`, like the `return` path keeps getting triggered. I'm observing this with this commit included. I'm on macOS, does `DISPLAY` even get set on macOS?

**Comment by doronbehar** [comment]
@blaenk `DISPLAY` is not set on macOS, I haven't took that in mind in https://github.com/kutsan/zsh-system-clipboard/commit/d771fae126f014826ae8d070efa2c762fe74d76b, I don't have a macOS to test this but I hope https://github.com/kutsan/zsh-system-clipboard/commit/5fe6dd7637b2ed11f43aa0aac165f660fb686d9d fixes this. Feel free to reopen if it doesn't fix.

**Comment by blaenk** [comment]
Seems to be fixed, thanks!
