### ISSUE TITLE
Help to be able to copy with CMD + V what I yank in vi mode in zsh

### ISSUE THREAD

**Issue by bjce** [kutsan/zsh-system-clipboard#29]
Hello

To start with, thank you very much to write the package!

I just switch from bash to zsh a few days ago. What I would like to do is to copy with <kbd>Cmd</kbd> + <kbd>v</kbd> what i just yanked with <kbd>y</kbd>

I manually insalled the package with the 2 following commands and didn't get any error: 
```
git clone https://github.com/kutsan/zsh-system-clipboard ~/.zsh/plugins/zsh-system-clipboard
source "$HOME/.zsh/plugins/zsh-system-clipboard/zsh-system-clipboard.zsh"
```

However what I yank is unfortunately not transferred to my keyboard. Do you have any idea about how I could go forward?

Many thanks for your help and your time

**Comment by kutsan** [comment]
I am honored, you're welcome.

You actually need to put this line to your `.zshrc` file. Can you confirm on that?

```
source "$HOME/.zsh/plugins/zsh-system-clipboard/zsh-system-clipboard.zsh"
```

And after that probably it's best to restart your shell to see changes.

**Comment by bjce** [comment]
Many thanks for your quick answer @kutsan. Sorry I didn't read the installation info properly. It was actually clear. And now it works just fine! many thanks again!

**Comment by kutsan** [comment]
No problem mate. There is no need to sorry. Have a good day.
