### ISSUE TITLE
structure the repo to attend to the zsh plugin convention

### ISSUE THREAD

**Issue by ninrod** [kutsan/zsh-system-clipboard#3]
most zsh plugins follow [this](https://github.com/zsh-users/zsh-completions) structure. If followed, most plugin managers will just install your plugin without hassle.

**Comment by kutsan** [comment]
So, seems like all I need to do is rename or link the `zsh-system-clipboard.zsh` file to `zsh-system-clipboard.plugin.zsh`?

Thanks by the way, I appericated it.

**Comment by ninrod** [comment]
yes, or do what I did in the pull. (#4)
