### ISSUE TITLE
Add option to copy to clipboard only with explict yanks

### ISSUE THREAD

**Issue by xiruizhao** [kutsan/zsh-system-clipboard#30]
Sometimes you just want to delete a line and don't want it to pollute your system clipboard. This option probably should also disable pasting from clipboard with vim puts, since you presumably want to use zsh's register for editing purposes. You can still paste from system clipboard with Cmd+V on macOS, not sure for other platforms.

**Comment by xiruizhao** [comment]
Never mind, I'll just fork and do my own thing. Great work!

**Comment by doronbehar** [comment]
@xiruizhao we maybe somewhat support the behavior you desire, and I'm personally using this configuration which is documented in the README. See https://github.com/kutsan/zsh-system-clipboard#configuration
