### ISSUE TITLE
Paste from clipboard not working in visual mode

### ISSUE THREAD

**Issue by Federico-Ciuffardi** [kutsan/zsh-system-clipboard#34]
Hi, pressing `p` in visual mode ignores the clipboard.

Is this just my problem or is the current plugin behavior?

Edit:
In normal mode works fine

**Comment by doronbehar** [comment]
I experience this as well. We should be able to fix it if will implement a function to be named:

```zsh
function zsh-system-clipboard-visual-put-replace-selection(){
;
}
zle -N zsh-system-clipboard-visual-put-replace-selection
```

Another function I noticed missing from visual mode is: `zsh-system-clipboard-visual-vi-delete`.
