### ISSUE TITLE
script could check for $WAYLAND_DISPLAY

### ISSUE THREAD

**Issue by Artturin** [kutsan/zsh-system-clipboard#41]
https://github.com/kutsan/zsh-system-clipboard/blob/48aa32645907534ac22168399960cbe44e7334f8/zsh-system-clipboard.zsh#L44

when xwayland is used the DISPLAY var will be set
at least some wayland compositors set WAYLAND_DISPLAY

**Comment by doronbehar** [comment]
Hello @Artturin .

The logic of choosing a clipboard method / program has been rewritten. Now, if if a user wishes to override the clipboard method to use Wayland, they should simply:

```zsh
export ZSH_SYSTEM_CLIPBOARD_METHOD=wlc # or wlp
```

See the updated README as well.

I hope this helps, regards.
