### ISSUE TITLE
Conflicts with oh-my-zsh?

### ISSUE THREAD

**Issue by Mo-tmd** [kutsan/zsh-system-clipboard#49]
I am using **oh-my-zsh**. I manually `source zsh-system-clipboard.sh` at the end of `.zshrc`. I am getting parser error near 'done' line 270. This doesn't happen when I don't use oh-my-zsh

**Comment by doronbehar** [comment]
Could you give more details about the error? Perhaps also add this:

```zsh
set -x
```

Right before oh-my-zsh loads plugins?

**Comment by Mo-tmd** [comment]
Thanks for the reply

Seems to work when I let oh-my-zsh source it for me
I assumed I need to source it myself since installations says it needs to be sourced after keybindings

**Comment by doronbehar** [comment]
If you think the README could be improved for oh-my-zsh installations, please share with us.

**Comment by Mo-tmd** [comment]
Perhaps just a note to add it to plugin section if using oh-my-zsh instead of sourcing it

**Comment by doronbehar** [comment]
If you could document in the README how does it work for you now - what line did you add to your .zshrc or whatever, it'd be great.
